set_schedule:
  target:
    entity:
      integration: intuis
      domain: climate
  fields:
    schedule_name:
      required: true
      example: "Winter Schedule"
      selector:
        text:

set_preset_mode_with_end_datetime:
  target:
    entity:
      integration: intuis
      domain: climate
  fields:
    preset_mode:
      required: true
      example: "Away"
      selector:
        select:
          options:
            - "Schedule"
            - "Frost Guard"
            - "Away"
    end_datetime:
      required: true
      selector:
        datetime:
